services:
  unifi-labeler:
    image: ghcr.io/mateuszmikrut/unalabeler:latest
    container_name: unifi-labeler
    restart: unless-stopped
    environment:
      UL_UNIFI_HOST: "https://unifi.example.com"
      UL_UNIFI_USER: "username"
      UL_UNIFI_PASS: "your-password-here" # Rather keep it in in secret store or .env file
      UL_UNIFI_SITE: "default"
      UL_REFRESH_MIN: "120"
      UL_LOGLEVEL: "INFO"
      UL_SHORTNAMES: "true"
      UL_DRYRUN: "false"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
